version: "1"
services:
  vue-todo:
    build: ./
    container_name: vue-todo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - 127.0.0.1:8432:8080
    restart: unless-stopped
